@baseUrl = http://localhost:3000

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "name": "test",
  "rollNo": 12
}

### Record Time
POST {{baseUrl}}/time HTTP/1.1
Content-Type: application/json

{
  "userId": "cm8jo58og0002tefcdjj23dhu",
  "time": 1232123
}

### Get Leaderboard
GET {{baseUrl}}/leaderboard